### ISSUE TITLE
M2MDevice::create_resource does not support vendor specific resources

### ISSUE THREAD

**Issue by davidchristine88** [ARMmbed/mbed-client#116]
I was trying to add some vendor specific resources with ID>=10241 and realized the method does not support anything other than standard LWM2M resources in Device object.   Is there an alternative method to do that?   Thanks in advance.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-477

**Comment by davidchristine88** [comment]
What does that mean?

**Comment by anttiylitokola** [comment]
Thanks for your report. ciarmcom is our internal bot account, it will raise ticket to our internal tools. 
What comes to the Device object, it will only support resources that are defined in the LWM2M Device object specification. In order to use vendor specific object id you must create custom object with that id. Here is an example how you can create custom object:
https://github.com/ARMmbed/mbed-client-examples/blob/master/source/main.cpp#L137

**Comment by davidchristine88** [comment]
I understand we could always create a custom object.   But is there a near future plan to support vendor specific Device Object resources with ID greater or equal to 10241?   Thanks.

**Comment by teetak01** [comment]
Hi, the vendor specific object is defined by the object ID range, so when object ID is >=10241 it is speficied as Vendor ID. Check this specification here for reserved ranges on Object IDs and Resource IDs. So to clarify, Object ID:s and Resource ID:s are different things. 

http://technical.openmobilealliance.org/Technical/technical-information/omna/lightweight-m2m-lwm2m-object-registry

Specification does not indicate custom resources can be added to OMA objects (Device object, firmware object, etc).

**Comment by davidchristine88** [comment]
Thanks for the clarification, I am slowly learning the specifics of the LWM2M spec - I guess I got that mixed up earlier.
