### ISSUE TITLE
m2mstring tries to malloc in a while loop

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client#138]
What is supposed to release memory in mbedOS, when busy looping in malloc_never_null().

https://github.com/ARMmbed/mbed-client/blob/master/source/m2mstring.cpp#L31

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-548

**Comment by mlnx** [comment]
@yogpan01 Could you please comment on this?

**Comment by yogpan01** [comment]
Hi, we might have an issue here , in case we run out of memory that we are in endless loop. Because we haven't seen this yet so this has not been an issue. We will check this up to see how we can handle this no memory issue better. Although I believe if we ever reach this case, most probably the client will anyway crash as there is not enough memory to handle anything after that point. But we would try to exist from the endless loop. Thanks for reporting this issue.

**Comment by markus-becker-tridonic-com** [comment]
On the K64 with very few objects this might not be an issue. On other devices with less RAM and more objects than in the simple examples, this is getting more likely. How are you measuring RAM usage?

**Comment by yogpan01** [comment]
We are trying to get a unified RAM measurement tool which would give us more accurate idea about memory usage. Since mbed-client is available on Linux as well, some high end figure on RAM usage can be checked from there as well. Those may not be exactly valid for mbed OS but can give some idea about the memory usage.

**Comment by yogpan01** [comment]
We are working to fix this issue and will soon release the fix.

**Comment by mlnx** [comment]
I understand this change fixes the problem:
https://github.com/ARMmbed/mbed-client/commit/dc5e3410437cb74af7cb8c2686862d3ff623697f

**Comment by anttiylitokola** [comment]
Yes, that should solve the problem.
