### ISSUE TITLE
Missing Device Object Resources When Connected to Device Connector

### ISSUE THREAD

**Issue by kaishi78** [ARMmbed/mbed-client#147]
When my device client is connected to Leshan, I'm able to see all the resources I've created for the device object.  However, when connected to Device Connector, I'm only able to see /3/0.

Thanks in advance.

Kai

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-569

**Comment by yogpan01** [comment]
Its because the Leshan server implementation populates the whole Device Object when the device registers with /3/0 Device Object Instance. IDevice Connector is based on Resource Model structure so  the client has to explicitly send the individual resources as part of registration message for them to appear in the Device Connector side.
mbed Client has an API where you can decide if you would like your resource to be published as own resource.
Check in M2MBase class 
`virtual void set_register_uri( bool register_uri);`
If you set the value of the given resource as true then you can see that resource explicitly on Device Connector side.
