### ISSUE TITLE
Using rand() for port number generations will lead to collisions

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-client#265]
At the moment when you do IPv4 w/ mbed Client we're recommending this:

```cpp
// Randomizing listening port for Certificate mode connectivity
   _server_address = server_address;
    srand(time(NULL));
    uint16_t port = rand() % 65535 + 12345;
```

The birthday paradox tells us that with 500 devices we're getting a 85% chance of collisions. That is a lot. Apparently having collisions is really bad, as @KalleVayrynen and @teetak01 explained:

> Kalle Väyrynen [10:38 AM]  
> these NATs are problematic
> 
> Teemu Takaluoma [10:47 AM]  
> @janjongboom: client code should randomize the port-number to which it is listening normally, or is this not the case? I presume you are using mbed Client components
> 
> Kalle Väyrynen [10:49 AM]  
> I see client ports 5684 a lot
>
> Teemu Takaluoma [10:52 AM]  
> that port really should only be used for the connection going to server
> 
> Kalle Väyrynen [11:00 AM]  
> Logs of few days for domain 680b... shows, sometimes port looks random, sometimes 5684,  few IPv4 addresses among IPv6, and sometimes those addresses even changes

We should find a better way of distributing port numbers here. Maybe put it in SECURITY_H file? As we can then use a counter and put it there. This way we're limiting the number of devices that can connect to Connector severely.

**Comment by yogpan01** [comment]
The original problem is not here but in the underlying network stack which should be supporting randomize port functionality. There is a inherent drawback for this system that you can only connect a limited set of devices if all of them decide to share the same IP address which is a fundamental issue here. Not sure how we can address this issue, when it is actually infrastructure problem.

**Comment by janjongboom** [comment]
> decide to share the same IP address

Well, I'm assuming all my devices are behind a NAT, so not really a choice. Does 1000 devices on a single IP sound unreasonable?

**Comment by janjongboom** [comment]
FYI, there was a suggestion in #connector-service Slack to reject registration when a port number is already in use, making the device re-register (with another random number). That would help a bit (but not solve the underlying problem).

**Comment by teetak01** [comment]
Well, I think this is more of an IPv4 problem, but it seems that having real IPv6 anywhere is still a dream.

Of course in case someone wants to have a network of 1000 devices they might have to have internal sub-networks to handle it in IPv4.

**Comment by yogpan01** [comment]
> there was a suggestion in #connector-service Slack to reject registration when a port number is already in use
That's something server needs to address and client can handle the corresponding error message and retry with newer port.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-847

**Comment by kjbracey-arm** [comment]
> Does 1000 devices on a single IP sound unreasonable?

Extremely unreasonable. They end up sharing 65000 ports, causing exactly the sort of problems you're having here. Maybe not a problem if they were all talking to different servers, but if they're all talking to the same server, your collision chance approaches certainty. Servers are going to start getting upset with what comes out of the NAT.

If you want to run thousands of devices, you need more than 1 public IP address. That's why IoT is expected to use IPv6. (Tunneled over the IPv4 Internet if necessary).

> it seems that having real IPv6 anywhere is still a dream.

Not sure that IPv6 is that much of a dream - my domestic cable ISP activated IPv6 last year for all customers. I've currently got 72,000,000,000,000,000 IP addresses, without even asking for them.

If going through a NAT, port collisions from the server's view are nothing to do with client port selections. If you're going through a NAT, it's the NAT choosing the public port. And it distinguishes devices based on internal IP address.

So I don't see any mbed-client issue here.
