### ISSUE TITLE
Feature request: Creation or deletion initiated by a LWM2M server, client notifies its application.

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#270]
We would like to have the possibility to get a notification (callback or subscription) from the mbed-client when a object instance is created or deleted via a LWM2M server. This to inform the application to cope with the (dis)appearance of an instance.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-880

**Comment by yogpan01** [comment]
Hi,
Can you please elaborate your use case ? Which application needs to be informed about this ? There is already a callback which gets called when object instance is created
value_updated(<objectInstance object> , <Object Instance name>)
For deleted resources we are not sending any updates because those objects dont exist anymore.

**Comment by EduardPon** [comment]
Hello yogpan01,

A typical use case for our project is that we want to assign an _application function_ to handle/process a object instance. 

- The relation, 1 object instance is processed by 1 _application function_.
- Each object ID has a specific _application function_ to do its job. 

This way be we can dis/enabled specific features in our device via LWM2M commissioning. So this means when creating an object instance via a LWM2M server, a task is dynamically created to run the corresponding _application function_. But also visa versa, deleting the instance must kill it to free unused resources. 

I'm aware of the value_updated callbacks, but how should this work? I cannot set the callback via the LWM2M server creation proces.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
