### ISSUE TITLE
M2MBase::set_under_observation

### ISSUE THREAD

**Issue by karsev** [ARMmbed/mbed-client#313]
- Type: Bug
- Priority: Major

All resources are set under observation by default when resources are created (at register phase).
In the `void M2MBase::set_under_observation(bool observed, M2MObservationHandler *handler)` function the observed parameter should be checked and the M2MReportHandler object created according to the value of that parameter.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1115

**Comment by jankii01** [comment]
Internal issue - should not be handled in GitHub, better to raise internal JIRA ticket directly.

**Comment by MarceloSalazar** [comment]
Reopening, as this requires visibility from partners.

**Comment by yogpan01** [comment]
@MarceloSalazar This is part of optimization activity and we would like to handle it through one single channel. We are going to do more optimization and its easier for us to handle it together rather than random bits of issues spread everywhere.  I propose we close it here , we are already handling these kind of issues internally.

**Comment by MarceloSalazar** [comment]
Please do not close this ticket. Partners don't have an alternative way of keeping track of requests/issues and need to have visibility.

**Comment by yogpan01** [comment]
I dont see partners have opened this ticket. This has been an internal observation and is a part of bigger study and analysis. We collect all the findings at one place and resolve them together and our internal project tool is the right place because it involves certain techincal discussions which may not be ready to be released to open github issues. You can keep this ticket open but please dont expect updates on this frequently.
