### ISSUE TITLE
Cannot find any info about MEMORY_OPTIMIZED_API

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#451]
Can you please provide some more info about the MEMORY_OPTIMIZED_API.

Are there any penalties?

Can I enable this flag by adding it in mbed_app.json: 
`"macros": ["MEMORY_OPTIMIZED_API"]`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1604

**Comment by JanneKiiskila** [comment]
Hi @EduardPon ,

indeed - our information is now in the Cloud Client (visible only to partners) side of the tools. However, I'll paste the relevant information here. In short - it enables some newer APIs (that are not backwards compatible, but the changes is mostly just from string to char *).

### Memory optimizations (1st phase).

See chapter Memory savings for more details.
mbed-client-c and mbed-client have a new flag - MEMORY_OPTIMIZED_API - which removes a few old methods and enables a bit more memory savings (in non-backwards compatible way). It is not defined by default.

### Memory savings

See the table for the sizeof(object) information.

| Class               | Before                | After                       |
|---------------------|-----------------------|-----------------------------|
| M2MBase             | 108                   |  32                         |
| M2MObject           | 128                   |  48                         |
| M2MObjectInstance   | 128                   |  48                         |
| M2MResource         | 240                   | 108                         |
| M2MResourceInstance | 216                   |  80                         |
| M2MDevice           | 132                   |  52                         |
| M2MFirmware         | 132                   |  52                         |
| M2MServer           | 132                   |  52                         |
| M2MSecurity         | 136                   |  56                         |
| M2MBlockMessage     |  24                   |  20                         |
| M2MReportHandler    |  72                   |  76                         |


### Compatibility issues

In many places, internal storage has been changed from `m2m::String` to `char *` or `const char *` to save memory.

* The `name()` methods are NOT anymore backwards compatible - they return `char *` instead of `String &`.
* Data duplication has been removed from the C/C++ objects (same data was both in C++ object and C-struct).

Most methods returning a string have been changed to use `char *` (to save memory - string class introduces extra 8 bytes of overhead per instance compared to `char *`). Changes have been made in the following classes and methods:


| Class | Before | After | Explanation |
|-------|--------|-------|-------------|
| M2MBase |      |       |     |
|         | set_interface_description() | - | Removed if MEMORY_OPTIMIZED_API defined. |
|         | set_resource_type()         | - | Removed if MEMORY_OPTIMIZED_API defined. |
|         | set_resource_type()         | - | Removed if MEMORY_OPTIMIZED_API defined. |
|         | string & name()             | const char * name() | Type changed from String ref char pointer. |
|         | string & interface_description() | const char * interface_description() | Type changed from String ref char pointer. |
|         | string & resource_type()         | const char * resource_type() | Type changed from String ref char pointer. |
|         | string & uri_path()              | const char * uri_path() | Type changed from String ref char pointer. |
|         | handle_observation_attribute(char *&query) | handle_observation_attribute(const char *query); | Type changed char reference pointer to const char pointer. |
|         | set_uri_path(constr string &path) |  -  | Method removed. |
|         | string &uri_path() const; |  -  | Method removed. |
| M2MObservationHandler |     |       |        |
|                       | resource_to_be_deleted(constr String &resource_name) | resource_to_be_deleted(M2MBase *base) | String ref to M2MBase object pointer. |
| M2MResourceInstance   |     |       |        |
|                       | const String& object_name() | virtual const char* object_name() | Returns char pointer instead of string ref. |

If you want to use newer memory optimized API - you have to use at least [mbed-OS-5.3.2](https://github.com/ARMmbed/mbed-os/releases/tag/mbed-os-5.3.2) due to mbed-client-c dependency.

**Comment by JanneKiiskila** [comment]
Please let us know if this is enough information.

Best Regards,


Janne

**Comment by JanneKiiskila** [comment]
Closing out, hopefully you have the information you need. 
Please raise a new ticket, if you need more information.

**Comment by EduardPon** [comment]
Thanks, this info is very helpful.
