### ISSUE TITLE
Resources not allowed to be read, do return data in TLV structure.

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#502]
So if a GET is performed on an object instance level, a TLV structure is returned containing all resource ID's and corresponding data.  Literally all resources are returning data, including the ones that are not allowed to do (operations PUT_ALLOWED, POST_ALLOWED, etc).

I would assume that these resources must be skipped during the TLV creation.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1749

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
