### ISSUE TITLE
LwM2M Resource & Object Registry implementations

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-client#504]
Before I start writing code that already exists; Does anybody have a repository laying around with implementations of some of the standard resources and objects for the mbed LwM2M Client?

http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1842

**Comment by yogpan01** [comment]
Hi @loverdeg-ep There is a support for Device , Firmware and Security object in mbed-client as for the other Objects , you  can implement those using existing M2MObject, M2MObjectInstance and M2MResource classes.

**Comment by loverdeg-ep** [comment]
Could a reference implementation of a multi-instance object be provided?

“LWM2M Server” is multi-instance but I’d like to have a non-mandatory Object to use as a reference as well.
DevCapMgmt or one of the ipso objects would do fine.

I’ve been attempting to implement an ipso Accelerometer object; Understanding how to use m2mObject and m2mObjectInstance has proven to be a non-trivial task.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
