### ISSUE TITLE
Write to resource with multiple values does update instead of replace

### ISSUE THREAD

**Issue by kmdewaal** [ARMmbed/mbed-client#507]
Given a resource defined with multiple instances, type string.

Problem: It is NOT possible to replace the content of the resource with a new value with less instances.
Example:
Existing value of the resource is [“one”, “two”, “three”]
Then write the new value [“aa”, “bb”]
Expected result is [“aa”, “bb”]
Actual result is: [“aa”, “bb”, “three”]

Relevant bits of the LWM2M specification:
Paragraph 5.4.3 Write on page 35 of OMA-TS-LightweightM2M-V1_0-20170208.pdf states:
LwM2M Client and LwM2M Server MUST support the following mechanisms to change multiple Resources or an array of Resource Instances: 
Replace: replaces the Object Instance or the Resource(s) with the new value provided in the "Write" operation. 
Partial Update: adds or updates Resources provided in the new value and leaves other existing Resources unchanged. 
 
Paragraph 8.2.5, "Device Management & Service Enablement Interface", page 77, states:
A CoAP PUT is used for the Replace and CoAP POST is used for Partial Update mechanism of the "Write" operation as described in 5.4.3.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1859

**Comment by aewp2** [comment]
Hi Klaas
In the LWM2M spec:
PUT does a replace
POST does a partial update
So is it correct to assume you are doing a PUT, via a Leshan server?

**Comment by kmdewaal** [comment]
Hi Amyas,

Yes, correct, we actually do a HTTP PUT from the Commissioning-Tool to the
Leshan server and then the Leshan server generates a CoAP PUT to the MBED
device. I can provide a Wireshark pcapng file if that is useful.

**Comment by yogpan01** [comment]
HI @kmdewaal,
Is the issue that PUT should remove the existing resource ? Sorry I didn't quite understand the issue.
You mentioned that you write with 2 resource instance value (when there were 3 resource instances) and those are updated but then the third value is untouched because its not updated.
Do you mean the third resource instances be deleted in this case ? The spec is a bit ambiguous for me to follow here, can you please update how do you interpret this.

**Comment by kmdewaal** [comment]
Hi @yogpan01 ,
I do agree that the spec about multi-instance resources is not very clear.
My interpretation is that the new resource value in the PUT should completely replace the old/existing resource value. In my example the old/existing resource value is an array of three strings. When the new resource value in the PUT is an array of two strings, as in my example, the final value of the resource should be the array of two strings, so exactly the same as the new resource value in the PUT.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
