### ISSUE TITLE
TLV format not supported for single value read and write

### ISSUE THREAD

**Issue by kmdewaal** [ARMmbed/mbed-client#508]
The MBED implementation acccepts only the TLV format for single-value write requests. It does accept only type "text'. The LWM2M standard specifies that for singlle-value requests the implementation of "text" is mandatory and that other formats such as TLV are optional.

However, the Leshan LWM2M server uses by default the TLV format for both multi-value and single-value read and write requests.
 This means that, when using the Leshan server for testing and debugging, you must always, on every device selected, change the message type from TLV to Text. 
It would be very convenient for those using the Leshan LWM2M server if the MBED implementation also supports the TLV format for single-value resource access.

As the TLV format is already supported for multi-value resource access it might be a limited effort to implement this.

**Comment by yogpan01** [comment]
Thanks for reporting, We will check and fix the issue.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
