### ISSUE TITLE
Add support for TLV binary floats

### ISSUE THREAD

**Issue by ghseb** [ARMmbed/mbed-client#514]
It seems that the current mbed-client does not support binary encoded floats as specified in the coap specification [OMA-TS-LightweightM2M-V1_0-20170208-A](http://www.openmobilealliance.org/release/LightweightM2M/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf) Appendix  C. 

Implementation could be similar to #488

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1935

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.

**Comment by JanneKiiskila** [comment]
This issue has been fixed to Cloud Client.
