### ISSUE TITLE
Coap RST messages are ignored

### ISSUE THREAD

**Issue by cdboutin** [ARMmbed/mbed-client#517]
In an OBSERVE context, the server may send a RST message indicating that it is not interested in receiving notifications anymore. The mbed-client library successfully parses the RST message but ignores it. Erroneously, the device then keep notifying the server about new resource values.

According to the LWM2M Technical Spec (section 8.2.6), the client shall not rely on the token value of the Rst message to conclude anything about the resource/object concerned by the Reset message. The Message ID should be used instead. 

Function M2MNsdlInterface::received_from_server_callback() uses the token value by calling  M2MNsdlInterface::find_resource(). As the token of a Reset message has a null length, find_ressource() returns a null pointer and the resource is not successfully removed from the observation list.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2134

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
