### ISSUE TITLE
Notify users if Registration Updates failed

### ISSUE THREAD

**Issue by ghseb** [ARMmbed/mbed-client#518]
Currently a user gets no notifications if registration updates failed or if the registration has already timed out due to connectivity issues or similar. It would be helpful to get such a notification as additional M2MInterface::Error in order to allow a user to react accordingly.

Br,
Sebastian

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2137

**Comment by yogpan01** [comment]
Thanks for reporting. We will check and see how we can improve this experience.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
