### ISSUE TITLE
Unsolicited messages or device-initiated observation possible?

### ISSUE THREAD

**Issue by amq** [ARMmbed/mbed-client#521]
I'l like to avoid having the application start the observation each time the device registers. With connectivity like cellular it causes additional traffic and is prone to errors, especially considering that the device goes off/online often, for short periods.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2162

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.

**Comment by teetak01** [comment]
@amq this actually sounds like that your device has pre-subscriptions enabled, thus server will automatically send subscription requests after registering.

For Cloud Client we are adding improvements for optimizing this kind of traffic in future release.
