### ISSUE TITLE
mbed-client on Mac

### ISSUE THREAD

**Issue by markushx** [ARMmbed/mbed-client#88]
```mbed-client-linux-example``` compiles just fine on Mac as well, when you add 
```
    "osx": {
      "mbed-client-linux": "~0.0.9",
      "mbed-client-mbedtls": "~0.0.2"
    }
```
to the module.json of mbed-client.

Would you consider adding it?

**Comment by yogpan01** [comment]
Thanks for this update. We will check when we can add this into the repo.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-418

**Comment by Charlyo** [comment]
Doesn't work with the latest mbed-linux-client and it's dependencies.

**Comment by jankii01** [comment]
Hi,

though it's easy now apparently to get it working on Mac like that - it's still not going to get fixed by us to work like that. Reason being that if we start saying it's an supported environment - we have to start testing everything in the Mac environment - effectively doubling our platform verification effort in that respect. So, unfortunately this is not likely to get fixed.
